import { appSchema, tableSchema } from '@nozbe/watermelondb';

export const schema = appSchema({
  version: 1,
  tables: [
    tableSchema({
      name: 'customers',
      columns: [
        { name: 'name', type: 'string' },
        { name: 'email', type: 'string', isOptional: true },
        { name: 'phone', type: 'string', isOptional: true },
        { name: 'gst_number', type: 'string', isOptional: true },
        { name: 'pan_number', type: 'string', isOptional: true },
        { name: 'address', type: 'string', isOptional: true },
        { name: 'city', type: 'string', isOptional: true },
        { name: 'state', type: 'string', isOptional: true },
        { name: 'state_code', type: 'string', isOptional: true },
        { name: 'pincode', type: 'string', isOptional: true },
        { name: 'country', type: 'string' },
        { name: 'contact_person', type: 'string', isOptional: true },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'outstanding_amount', type: 'number' },
        { name: 'is_favorite', type: 'boolean' },
        { name: 'avatar_color', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'is_deleted', type: 'boolean' },
      ],
    }),
    tableSchema({
      name: 'products',
      columns: [
        { name: 'name', type: 'string' },
        { name: 'description', type: 'string', isOptional: true },
        { name: 'sku', type: 'string', isOptional: true },
        { name: 'barcode', type: 'string', isOptional: true },
        { name: 'category', type: 'string', isOptional: true },
        { name: 'unit', type: 'string' },
        { name: 'purchase_price', type: 'number' },
        { name: 'selling_price', type: 'number' },
        { name: 'tax_rate', type: 'number' },
        { name: 'tax_type', type: 'string' },
        { name: 'discount', type: 'number' },
        { name: 'stock_quantity', type: 'number', isOptional: true },
        { name: 'low_stock_threshold', type: 'number', isOptional: true },
        { name: 'hsn_code', type: 'string', isOptional: true },
        { name: 'image_uri', type: 'string', isOptional: true },
        { name: 'is_service', type: 'boolean' },
        { name: 'is_active', type: 'boolean' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'is_deleted', type: 'boolean' },
      ],
    }),
    tableSchema({
      name: 'invoices',
      columns: [
        { name: 'invoice_number', type: 'string' },
        { name: 'customer_id', type: 'string', isIndexed: true },
        { name: 'subtotal', type: 'number' },
        { name: 'discount_amount', type: 'number' },
        { name: 'discount_percent', type: 'number' },
        { name: 'tax_amount', type: 'number' },
        { name: 'tax_type', type: 'string' },
        { name: 'cgst_amount', type: 'number' },
        { name: 'sgst_amount', type: 'number' },
        { name: 'igst_amount', type: 'number' },
        { name: 'round_off', type: 'number' },
        { name: 'total_amount', type: 'number' },
        { name: 'amount_paid', type: 'number' },
        { name: 'status', type: 'string' },
        { name: 'due_date', type: 'number' },
        { name: 'invoice_date', type: 'number' },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'terms_conditions', type: 'string', isOptional: true },
        { name: 'shipping_address', type: 'string', isOptional: true },
        { name: 'shipping_charges', type: 'number' },
        { name: 'reference_number', type: 'string', isOptional: true },
        { name: 'is_recurring', type: 'boolean' },
        { name: 'recurring_interval', type: 'string', isOptional: true },
        { name: 'type', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'is_deleted', type: 'boolean' },
      ],
    }),
    tableSchema({
      name: 'invoice_items',
      columns: [
        { name: 'invoice_id', type: 'string', isIndexed: true },
        { name: 'product_id', type: 'string', isOptional: true, isIndexed: true },
        { name: 'name', type: 'string' },
        { name: 'description', type: 'string', isOptional: true },
        { name: 'hsn_code', type: 'string', isOptional: true },
        { name: 'unit', type: 'string' },
        { name: 'quantity', type: 'number' },
        { name: 'unit_price', type: 'number' },
        { name: 'discount_percent', type: 'number' },
        { name: 'discount_amount', type: 'number' },
        { name: 'tax_rate', type: 'number' },
        { name: 'tax_amount', type: 'number' },
        { name: 'total', type: 'number' },
        { name: 'created_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'payments',
      columns: [
        { name: 'payment_number', type: 'string' },
        { name: 'invoice_id', type: 'string', isIndexed: true },
        { name: 'customer_id', type: 'string', isIndexed: true },
        { name: 'amount', type: 'number' },
        { name: 'payment_mode', type: 'string' },
        { name: 'reference_number', type: 'string', isOptional: true },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'payment_date', type: 'number' },
        { name: 'status', type: 'string' },
        { name: 'receipt_number', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'is_deleted', type: 'boolean' },
      ],
    }),
    tableSchema({
      name: 'expenses',
      columns: [
        { name: 'expense_number', type: 'string' },
        { name: 'category_id', type: 'string', isOptional: true, isIndexed: true },
        { name: 'amount', type: 'number' },
        { name: 'description', type: 'string' },
        { name: 'date', type: 'number' },
        { name: 'receipt_uri', type: 'string', isOptional: true },
        { name: 'is_recurring', type: 'boolean' },
        { name: 'recurring_interval', type: 'string', isOptional: true },
        { name: 'payment_mode', type: 'string' },
        { name: 'vendor_name', type: 'string', isOptional: true },
        { name: 'invoice_number', type: 'string', isOptional: true },
        { name: 'tax_amount', type: 'number', isOptional: true },
        { name: 'is_deductible', type: 'boolean' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'is_deleted', type: 'boolean' },
      ],
    }),
    tableSchema({
      name: 'expense_categories',
      columns: [
        { name: 'name', type: 'string' },
        { name: 'icon', type: 'string', isOptional: true },
        { name: 'color', type: 'string', isOptional: true },
        { name: 'is_default', type: 'boolean' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'business_profiles',
      columns: [
        { name: 'name', type: 'string' },
        { name: 'email', type: 'string', isOptional: true },
        { name: 'phone', type: 'string', isOptional: true },
        { name: 'address', type: 'string', isOptional: true },
        { name: 'city', type: 'string', isOptional: true },
        { name: 'state', type: 'string', isOptional: true },
        { name: 'state_code', type: 'string', isOptional: true },
        { name: 'pincode', type: 'string', isOptional: true },
        { name: 'country', type: 'string' },
        { name: 'gst_number', type: 'string', isOptional: true },
        { name: 'pan_number', type: 'string', isOptional: true },
        { name: 'logo_uri', type: 'string', isOptional: true },
        { name: 'signature_uri', type: 'string', isOptional: true },
        { name: 'bank_name', type: 'string', isOptional: true },
        { name: 'bank_account_number', type: 'string', isOptional: true },
        { name: 'bank_ifsc', type: 'string', isOptional: true },
        { name: 'upi_id', type: 'string', isOptional: true },
        { name: 'website', type: 'string', isOptional: true },
        { name: 'invoice_prefix', type: 'string' },
        { name: 'invoice_start_number', type: 'number' },
        { name: 'default_payment_terms', type: 'string', isOptional: true },
        { name: 'default_notes', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'ledger_entries',
      columns: [
        { name: 'customer_id', type: 'string', isIndexed: true },
        { name: 'type', type: 'string' },
        { name: 'amount', type: 'number' },
        { name: 'balance', type: 'number' },
        { name: 'description', type: 'string' },
        { name: 'reference_id', type: 'string', isOptional: true },
        { name: 'reference_type', type: 'string', isOptional: true },
        { name: 'date', type: 'number' },
        { name: 'created_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'notifications',
      columns: [
        { name: 'title', type: 'string' },
        { name: 'message', type: 'string' },
        { name: 'type', type: 'string' },
        { name: 'is_read', type: 'boolean' },
        { name: 'action_screen', type: 'string', isOptional: true },
        { name: 'action_params', type: 'string', isOptional: true },
        { name: 'reference_id', type: 'string', isOptional: true },
        { name: 'reference_type', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'backup_metadata',
      columns: [
        { name: 'file_name', type: 'string' },
        { name: 'file_size', type: 'number' },
        { name: 'backup_type', type: 'string' },
        { name: 'status', type: 'string' },
        { name: 'google_drive_id', type: 'string', isOptional: true },
        { name: 'description', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
      ],
    }),
  ],
});
