export const StorageKeys = {
  THEME: '@invoicehub/theme',
  LANGUAGE: '@invoicehub/language',
  CURRENCY: '@invoicehub/currency',
  DATE_FORMAT: '@invoicehub/date_format',
  TIME_FORMAT: '@invoicehub/time_format',
  AUTH_TOKEN: '@invoicehub/auth_token',
  REFRESH_TOKEN: '@invoicehub/refresh_token',
  USER_ID: '@invoicehub/user_id',
  USER_EMAIL: '@invoicehub/user_email',
  BUSINESS_PROFILE_CACHE: '@invoicehub/business_profile',
  TAX_SETTINGS_CACHE: '@invoicehub/tax_settings',
  INVOICE_SEQUENCE: '@invoicehub/invoice_sequence',
  LAST_BACKUP: '@invoicehub/last_backup',
  ONBOARDING_COMPLETE: '@invoicehub/onboarding_complete',
  NOTIFICATION_PREFERENCES: '@invoicehub/notification_preferences',
  DEFAULT_PAYMENT_TERMS: '@invoicehub/default_payment_terms',
  DEFAULT_NOTES: '@invoicehub/default_notes',
  PRINT_PREFERENCES: '@invoicehub/print_preferences',
  CUSTOMER_SORT_PREFERENCE: '@invoicehub/customer_sort',
  INVOICE_SORT_PREFERENCE: '@invoicehub/invoice_sort',
  PRODUCT_SORT_PREFERENCE: '@invoicehub/product_sort',
  DASHBOARD_WIDGETS: '@invoicehub/dashboard_widgets',
  SEARCH_HISTORY: '@invoicehub/search_history',
  GST_STATE_CODE: '@invoicehub/gst_state_code',
  IS_IGST_APPLICABLE: '@invoicehub/is_igst_applicable',
  INVOICE_PREFIX: '@invoicehub/invoice_prefix',
  EXPENSE_PREFIX: '@invoicehub/expense_prefix',
  PAYMENT_PREFIX: '@invoicehub/payment_prefix',
  FINANCIAL_YEAR_START: '@invoicehub/financial_year_start',
  TAX_REGISTRATION: '@invoicehub/tax_registration',
  BANK_ACCOUNT_CACHE: '@invoicehub/bank_account_cache',
  APP_FIRST_LAUNCH: '@invoicehub/app_first_launch',
  LAST_SYNC_TIMESTAMP: '@invoicehub/last_sync_timestamp',
  BACKUP_ENCRYPTION_KEY: '@invoicehub/backup_encryption_key',
  APP_STATE: '@invoicehub/app_state',
  INVOICE_DRAFT: '@invoicehub/invoice_draft',
  DASHBOARD_STATE: '@invoicehub/dashboard_state',
  SETTINGS_STATE: '@invoicehub/settings_state',
} as const;

export type StorageKey = (typeof StorageKeys)[keyof typeof StorageKeys];
